import { readFileSync, readdirSync, writeFileSync } from 'node:fs'

// Migrations remain the source of truth for both fresh installs and upgrades.
const migrationsDirectory = new URL('../supabase/migrations/', import.meta.url)
const setupFile = new URL('../supabase/setup.sql', import.meta.url)
const files = readdirSync(migrationsDirectory)
  .filter((file) => file.endsWith('.sql'))
  .sort()

if (!files.length) throw new Error('No SQL migrations found.')
if (process.argv.slice(2).some((arg) => arg !== '--check')) {
  throw new Error('Usage: node scripts/build-setup.mjs [--check]')
}

const sections = files.map((file) => {
  const lines = readFileSync(new URL(file, migrationsDirectory), 'utf8')
    .replace(/\r\n/g, '\n')
    .trimEnd()
    .split('\n')
  const start = lines.findIndex((line) => /^begin;$/i.test(line.trim()))
  if (
    start < 0 ||
    !lines.slice(0, start).every((line) => !line.trim() || line.trim().startsWith('--')) ||
    !/^commit;$/i.test(lines.at(-1).trim())
  ) {
    throw new Error(`${file}: expected leading comments followed by BEGIN and a final COMMIT.`)
  }

  // Replace only the outer transaction, never PL/pgSQL BEGIN/END blocks.
  const body = lines
    .slice(start + 1, -1)
    .join('\n')
    .trim()
  if (/^\s*(begin|commit|rollback)\s*;/im.test(body)) {
    throw new Error(`${file}: nested transaction control needs review before bundling.`)
  }
  return `-- Included migration: ${file}\n${body}`
})

const sql = `-- SnoiCafe: complete database setup for a NEW Supabase project.
-- Copy this entire file into the Supabase SQL Editor and run as the database owner.
-- Includes all ${files.length} migrations through ${files.at(-1)}; do not run them separately.
-- Existing kitchens: apply only missing migrations in order instead of this file.
-- After success, initialize your kitchen with the bootstrap_kitchen query in README.md.
-- Generated by pnpm db:setup. Edit the migrations, not this file.

begin;

do $$
begin
  if to_regclass('public.kitchens') is not null then
    raise exception 'SnoiCafe is already installed. Apply only missing migrations in order; do not run setup.sql on an existing installation.';
  end if;
end $$;

${sections.join('\n\n')}

commit;
`

if (process.argv.includes('--check')) {
  let existing
  try {
    existing = readFileSync(setupFile, 'utf8')
  } catch (error) {
    if (error.code !== 'ENOENT') throw error
  }
  if (existing !== sql) {
    console.error(
      'supabase/setup.sql is missing or outdated. Run pnpm db:setup and commit the result.',
    )
    process.exitCode = 1
  } else {
    console.log(`supabase/setup.sql is up to date (${files.length} migrations).`)
  }
} else {
  writeFileSync(setupFile, sql)
  console.log(`Generated supabase/setup.sql from ${files.length} migrations.`)
}
